# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('fb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('has_fb_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(default='Text', max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('fbuser', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fb_chatbot.FacebookUser')),
                ('qrcode', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fb_chatbot.QRCode')),
            ],
        ),
    ]
